# Generated by Django 6.0.6 on 2026-09-28 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("convenios", "0001_initial"),
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Licencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "convenio",
                    models.ForeignKey(
                        db_column="id_convenio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="convenios.convenio",
                    ),
                ),
            ],
            options={
                "verbose_name": "licencia",
                "verbose_name_plural": "licencias",
            },
        ),
        migrations.CreateModel(
            name="SolicitudLicencia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("motivo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        db_column="legajo_empleado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_licencia",
                        to="empleados.empleado",
                    ),
                ),
                (
                    "licencia",
                    models.ForeignKey(
                        db_column="id_licencia",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="licencias.licencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud de licencia",
                "verbose_name_plural": "solicitudes de licencia",
            },
        ),
    ]
