# Generated by Django 6.0.6 on 2026-09-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convenios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
