# Generated by Django 6.0.6 on 2026-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("convenios", "0002_convenio_activo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convenio",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
