classDiagram
    class Empleado {
        -Int legajo
        -String nombre
        -Date fechaIngreso

        +solicitarLicencia(TipoLicencia tipo, Date inicio, Date fin) SolicitudLicencia
        +notificarHorasExtras(TipoHoraExtra tipo, Float horas, Date fecha) NotificaciónHorasExtras
    }

    class RecursosHumanos {
        +aprobarLicencia(SolicitudLicencia solicitud)
        +rechazarLicencia(SolicitudLicencia solicitud)
        +aprobarHorasExtras(NotificaciónHorasExtras notificación)
        +rechazarHorasExtras(NotificaciónHorasExtras notificación)
    }

    class ConvenioDeTrabajo {
        -String nombre
        +calcularMultiplicador(TipoHoraExtra tipo) Float
    }

    class SolicitudLicencia {
        -Date fechaInicio
        -Date fechaFin
        -EstadoSolicitud estado
        +aprobar()
        +rechazar()
        +cancelar()
    }

    class NotificaciónHorasExtras {
        -Date fecha
        -Float horas
        -EstadoNotificación estado
        +aprobar()
        +rechazar()
        +cancelar()
    }

    class Reporte {
        -Date fechaGeneracion
        -Date fechaInicio
        -Date fechaFin
        +exportar()
    }

    Empleado --> ConvenioDeTrabajo : rige bajo
    Empleado --> SolicitudLicencia : genera
    Empleado --> NotificaciónHorasExtras : genera
    Reporte --> Empleado : corresponde a
    RecursosHumanos --> NotificaciónHorasExtras : autoriza
    RecursosHumanos --> SolicitudLicencia : evalúa
