erDiagram
    CONVENIO_DE_TRABAJO {
        int id PK
        string nombre
    }
    
    EMPLEADO {
        int legajo PK
        int id_convenio FK
        string nombre
        date fechaIngreso
    }
    
    HORA_EXTRA {
        int id PK
        int id_convenio FK
        string tipo
        string descripcion
        float multiplicador
    }
    
    LICENCIA {
        int id PK
        int id_convenio FK
        string tipo
        string descripcion
    }
    
    REPORTE {
        int id PK
        int legajo FK
        date fechaGeneracion
        date fechaInicio
        date fechaFin
    }
    SOLICITUD_LICENCIA {
        int id PK
        int legajo_empleado FK
        int id_licencia FK
        date fechaInicio
        date fechaFin
        string estado
        string motivo
    }
    
    NOTIFICACION_HORAS_EXTRAS {
        int id PK
        int legajo_empleado FK
        int id_hora_extra FK
        date fecha
        float horas
        string estado
        string motivo
    }
    

    CONVENIO_DE_TRABAJO ||--o{ EMPLEADO : "agrupa"
    CONVENIO_DE_TRABAJO ||--o{ HORA_EXTRA : "establece"
    CONVENIO_DE_TRABAJO ||--o{ LICENCIA : "establece"
    EMPLEADO ||--o{ REPORTE : "le corresponde"
    EMPLEADO ||--o{ NOTIFICACION_HORAS_EXTRAS : "genera"
    EMPLEADO ||--o{ SOLICITUD_LICENCIA : "genera"
    HORA_EXTRA ||--o{ NOTIFICACION_HORAS_EXTRAS : "corresponde a"
    LICENCIA ||--o{ SOLICITUD_LICENCIA : "corresponde a"
