stateDiagram-v2
    [*] --> Pendiente: Empleado notifica horas extras
    Pendiente --> Aprobada : RRHH aprueba la notificación
    Pendiente --> Rechazada : RRHH rechaza la notificación
    Pendiente --> Cancelado : Empleado cancela la notificación
    Aprobada --> Cancelado : Empleado cancela la notificación
    Aprobada --> [*]
    Rechazada --> [*]
    Cancelado --> [*]
