# Generated by Django 6.0.6 on 2026-09-28 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("convenios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "legajo",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("fecha_ingreso", models.DateField()),
                (
                    "convenio",
                    models.ForeignKey(
                        db_column="id_convenio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="convenios.convenio",
                    ),
                ),
            ],
            options={
                "verbose_name": "empleado",
                "verbose_name_plural": "empleados",
            },
        ),
    ]
