# Generated by Django 6.0.6 on 2026-09-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="nombre",
            field=models.CharField(max_length=255),
        ),
    ]
