# Generated by Django 6.0.6 on 2026-10-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleados", "0002_alter_empleado_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
