# Generated by Django 6.0.6 on 2026-09-28 01:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("convenios", "0001_initial"),
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoraExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "multiplicador",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "convenio",
                    models.ForeignKey(
                        db_column="id_convenio",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horas_extra",
                        to="convenios.convenio",
                    ),
                ),
            ],
            options={
                "verbose_name": "hora extra",
                "verbose_name_plural": "horas extras",
            },
        ),
        migrations.CreateModel(
            name="NotificacionHorasExtras",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateField()),
                (
                    "horas",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("motivo", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        db_column="legajo_empleado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notificaciones_horas_extras",
                        to="empleados.empleado",
                    ),
                ),
                (
                    "hora_extra",
                    models.ForeignKey(
                        db_column="id_hora_extra",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notificaciones",
                        to="horas_extras.horaextra",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación de horas extras",
                "verbose_name_plural": "notificaciones de horas extras",
            },
        ),
    ]
